replicaCount: 1

image:
  repository: Aezule/helm-chart
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: helm-chart.example.com
      paths:
        - /
  tls: []
