name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      helm_release:
        description: 'Helm'
        required: true
      namespace:
        description: 'Kubernetes'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          helm-version: v3.17.0


      - name: deploy helm chart
        run: helm upgrade --install ${{ github.event.inputs.helm_release }} ./helm-chart --namespace ${{ github.event.inputs.namespace }} --create-namespace
