name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      helm_release:
        description: 'Helm'
        required: true
      namespace:
        description: 'Kubernetes'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.0'

      - name: Verify Helm Version
        run: helm version

      - name: Configure Kubernetes
        uses: azure/k8s-set-context@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build Helm Chart
        run: |
          helm package ./helm -d ./helm/output  # Chemin mis à jour ici

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install devops-app ./helm/output/devops-app-*.tgz \
          --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/devops-autonomie \
          --set image.tag=latest
